version: '3.1'
services:
  postgres:
    image: 'postgres:9.5.14-alpine'
    volumes:
      - './init-postgres-db.sh:/docker-entrypoint-initdb.d/init-postgres-db.sh'
      - './data/postgres:/var/lib/postgresql/data'
    environment:
      POSTGRES_DB: tokenrate
      POSTGRES_USER: tokenrate
      POSTGRES_PASSWORD: tokenrate
    ports:
      - '127.0.0.1:5432:5432'
  pgadmin4:
    image: dpage/pgadmin4
    ports:
      - '127.0.0.1:9000:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: tokenrate@localhost
      PGADMIN_DEFAULT_PASSWORD: tokenrate
